### ISSUE TITLE
short dump in creating corrective maintenance order

### ISSUE THREAD

**Issue by ccandito** [codup/odoo-eam#38]
when creating a corrective maintenance order without any reference to a maintenance requent a shot dump's occurred in evaluating task field:
the system log is reported below:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1600, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1613, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4224, in _search
    query = self._where_calc(args)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4025, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/usr/lib/python2.7/dist-packages/odoo/osv/expression.py", line 1290, in to_sql
    q, p = self.__leaf_to_sql(leaf)
  File "/usr/lib/python2.7/dist-packages/odoo/osv/expression.py", line 1215, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term (u'category_id', u'in', {u'name': u'222'})

**Comment by ccandito** [comment]
thanks a lot
it's worked out perfectly.

I've three questions related to the PM app:

   - it's possible to use more than one task; I did some tests and it seems
   it doens't work properly
   - about the intervals, only the inferior limit is useful.... I don't
   understand when the superior limit is used
   - when Average Time (days) is used

thanks in advance
claudio candito

2017-06-13 16:47 GMT+02:00 wowas18 <notifications@github.com>:

**Comment by wowas18** [comment]
- Yes, it is possible to use unlimeted number of tasks. Can you share your tests?
- Intervals have tolerances and algorithm calculate date that it fell within their limits. If you no need tolerance, just set up low and high the same.
- Average Time (days) is period for calculate average utilization
