### ISSUE TITLE
[11.0] Getting Error only by adding the module folder in the addons path !

### ISSUE THREAD

**Issue by sjpatel21** [codup/odoo-eam#43]
Getting Strange error while just adding the addons directory in the odoo config file:

2017-12-19 06:08:57,789 20379 INFO ? odoo: database: default@default:default
2017-12-19 06:08:57,800 20379 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:9001
2017-12-19 06:08:57,912 20379 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2017-12-19 06:09:26,589 20379 INFO ? werkzeug: 127.0.0.1 - - [19/Dec/2017 06:09:26] "GET / HTTP/1.1" 500 -
2017-12-19 06:09:26,591 20379 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/sunny/.local/lib/python3.5/site-packages/werkzeug/serving.py", line 267, in run_wsgi
    execute(self.server.app)
  File "/home/sunny/.local/lib/python3.5/site-packages/werkzeug/serving.py", line 255, in execute
    application_iter = app(environ, start_response)
  File "/home/sunny/Work/odoo/odoo11/odoo/odoo/service/server.py", line 251, in app
    return self.app(e, s)
  File "/home/sunny/Work/odoo/odoo11/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/home/sunny/Work/odoo/odoo11/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/home/sunny/Work/odoo/odoo11/odoo/odoo/http.py", line 1297, in __call__
    self.load_addons()
  File "/home/sunny/Work/odoo/odoo11/odoo/odoo/http.py", line 1313, in load_addons
    manifest = ast.literal_eval(pycompat.to_native(manifest_data))
  File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
File "<unknown>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier

**Comment by MartinHeisig** [comment]
can confirm this. Get the same while adding the single mro-module or the whole repository to odoo.conf addon-path:

2018-01-25 14:52:46,470 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1297, in __call__
    self.load_addons()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1313, in load_addons
    manifest = ast.literal_eval(pycompat.to_native(manifest_data))
  File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
File "<unknown>", line 1
    ﻿# -*- coding: utf-8 -*-
    ^
SyntaxError: invalid character in identifier

**Comment by bgkerion** [comment]
probably it is because the module not really be ported on odoo 11.0. The commit history says that manifest files have been only renamed from version 10...

**Comment by bgkerion** [comment]
well running pycompat.to_native(manifest_data) on asset/__manifest__py I've obtain the following result:
`pycompat.to_native(manifest_data)
'\ufeff# -*- coding: utf-8 -*-\n##############################################################################\n#\n#    Odoo\n#    Copyright (C) 2013-2016 CodUP (<http://codup.com>).\n#\n##############################################################################\n\n{\n    \'name\': \'Assets\',\n    \'version\': \'1.10\',\n    \'summary\': \'Asset Management\',\n    \'description\': """\nManaging Assets in Odoo.\n===========================\nSupport following feature:\n    * Location for Asset\n    * Assign Asset to employee\n    * Track warranty information\n    * Custom states of Asset\n    * States of Asset for different team: Finance, Warehouse, Manufacture, Maintenance and Accounting\n    * Drag&Drop manage states of Asset\n    * Asset Tags\n    * Search by main fields\n    """,\n    \'author\': \'CodUP\',\n    \'website\': \'http://codup.com\',\n    \'category\': \'Industries\',\n    \'sequence\': 0,\n    \'depends\': [\'stock\'],\n    \'demo\': [\'asset_demo.xml\'],\n    \'data\': [\n        \'security/asset_security.xml\',\n        \'security/ir.model.access.csv\',\n        \'asset_view.xml\',\n        \'asset_data.xml\',\n        \'stock_data.xml\',\n        \'views/asset.xml\',\n    ],\n    \'installable\': True,\n    \'application\': True,\n}\n# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:'
`
there is the first character (\ufeff) actually invalid ... I haven't tried to remove it yet... ideas?

**Comment by bgkerion** [comment]
I've removed the first character using vim and set nobomb (https://gist.github.com/szydan/b225749445b3602083ed) and now the shown error is: `ModuleNotFoundError: No module named 'asset'`

**Comment by wshamasneh** [comment]
After placing the applications in the Addon folder the Odoo 11 CE has not started giving the following error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by arafatx** [comment]
Same issue !

**Comment by mediaengagers** [comment]
Try to use python2 instead of python3

**Comment by NikDhameliya** [comment]
Install Assets management module then try to install assets may be worked..

**Comment by HMMalek** [comment]
After placing the folders in addons and restarting the server, when I run Odoo (v11) I get a blank page: I tried moving one folder at a time into addons, still the same problem: blank page with the black header..
the character issue already fixed
using python 2.7

**Comment by wowas18** [comment]
Please download [version for Odoo 11](https://www.odoo.com/apps/modules/11.0/mro/).
