### ISSUE TITLE
Errors  v.13

### ISSUE THREAD

**Issue by jcerquin** [codup/odoo-eam#64]
It shows an error when I try to register a Maintenance Request
And another error is available parts are not shown on maintenance orders even though they exist in inventory

Error - Register Maintenance Request (SEND REQUEST):

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo13/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo13/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo13-custom-addons/mro/mro.py", line 337, in action_send
    request.write(value)
  File "/opt/odoo/odoo13/addons/mail/models/mail_thread.py", line 329, in write
    tracking = track_self.with_context(clean_context(self._context)).message_track(tracked_fields, initial_values)
  File "/opt/odoo/odoo13/addons/mail/models/mail_thread.py", line 656, in message_track
    if not subtype.exists():
AttributeError: 'str' object has no attribute 'exists'

**Comment by wowas18** [comment]
Thank you! Fixed in https://github.com/codup/odoo-eam/commit/7e4b49421c4664491c9180d293bba44fc8ed40f3
